version: "3.3"
#x-aliases:
#  - &restart
#    restart: always
#  - &logging
#    logging:
#      driver: json-file
#      options:
#        max-file: '5'
#        max-size: 10m

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
#    <<: *logging
#    <<: *restart
###
  app:
    build: .
    volumes:
      - ./data:/app
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
#    <<: *logging
#    <<: *restart


volumes:
  postgresql:
