version: '3'

services:

  db:
    image: "postgres:latest"
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
       - ./data/postgres/out/data:/var/lib/postgresql/data
       - ./data/postgres/out/logs:/logs

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_LOGIN
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASS
