version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
    - 5432:5432



#  pgadmin4:
#    image: dpage/pgadmin4
#    ports:
#      - 8080:80